server:
  port: 8082
spring:
  application:
    name: accessManagement
  datasource:
    url: jdbc:h2:mem:accessManagement
    username: {global.database.username}
    password: {global.database.password}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: {global.email.username}
    password: {global.email.password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
        smtp.from: {global.email.your-email}
    default-encoding: UTF-8
mail:
  from:
    name: Sachin

app:
  jwt:
    secret:
      key: { global.jwt.secret }
  permission:
    load:
      mode: update
    file:
      name: permission.json
  file:
    upload-dir: ./uploads/avatars
    storage:
      mapping: file:/var/identity-authorization/uploads/
  url:
    confirm-account: http://localhost:8082/public/auth/confirm-account
    password-reset: http://localhost:8082/public/auth/reset-password

logging:
  level:
    org.springframework: INFO





