name: Dev Branch - Clean Install Only

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    name: Clean Install (No Tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Clean Install
        run: ./mvnw clean install -DskipTests
