name: Build JAR and Docker Image

on:
  push:
    branches: [development]

jobs:
  build:
    name: Build Spring Boot JAR and Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        run: ./mvnw clean install -DskipTests

      - name: Build Docker Image using Dockerfile
        run: docker build -t myapp:latest .
